name: MirrorHack Submission (English)
description: Submit your project for MirrorHack. (Approx. 5-10 minutes)
title: "[<CATEGORY>]: <PROJECT_NAME> by <TEAM_NAME> "
labels: ["v1.0", "submission"]
assignees:
  - codebender828
  - zhangryan
  - hikergit
  # - Chris Zhu Github
body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating in the MirrorHack 1.0 hackathon!

  # Project theme
  - type: dropdown
    id: project_theme
    attributes:
      label: Project Theme
      description: What category does your hack belong to?
      options:
        - "Web 3 Category: Authentication"
        - "Web 3 Category: Launchpads"
        - "Web 3 Category: Game Distribution"
        - "AI Category: Token Price Prediction"
        - "AI Category: Talking AI with Genetic Breeding"
        - "Gaming Category: Frameworks for game physics, motion"
        - "Gaming Category: Game rendering frameworks"
        - "Gaming Category: Tooling for game developers, designers and market operators"
        - "Other"
    validations:
      required: true

  # Project name
  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: What is the name of your project
      placeholder: ex. My awesome MirrorHack project
    validations:
      required: true

  # Project short description
  - type: input
    id: project_description
    attributes:
      label: Short Project Description
      description: Simple crisp description of your project
      placeholder: ex. Passwordless authentication for Web 3
    validations:
      required: true

  # Project members
  - type: textarea
    id: team_members
    attributes:
      label: 🏀 Team Members
      description: Mention their Names & tag their GitHub handles
      value: |
        1. Member A - @memberA
        2. Member B - @memberB
        3. Member C - @memberC
    validations:
      required: true

  # Project demo video link
  - type: input
    id: demo_link
    attributes:
      label: 🎥 Demo Video Link
      description: Please provide the link to your hack's demo video. (Your video should not exceed 3 minutes in length)
      placeholder: https://youtu.be/dQw4w9WgXcQ
    validations:
      required: true

  # Project Live Demo (Not required)
  - type: input
    id: live_demo_link
    attributes:
      label: ⚡️ Live Demo URL
      description: Is your project already deployed? Please share a link to the live working demo 💪🏾
      placeholder: https://youtu.be/dQw4w9WgXcQ
    validations:
      required: false

  # Project presentation url
  - type: input
    id: presentation_link
    attributes:
      label: 🔖 Presentation Link
      description: Please provide the link to your hack's presentation
      placeholder: https://some.link/with/your/presentation.pdf
    validations:
      required: true

  # Project theme
  - type: input
    id: source_code_link
    attributes:
      label: 💻 Hack Source Code (GitHub)
      description: Please provide the link to your hack's GitHub repository. Your codebase should be public.
      placeholder: https://github.com/my-team-hack/source-code
    validations:
      required: true
  - type: textarea
    id: pitch
    attributes:
      label: 🔥 Your Pitch
      description: Kindly write a pitch for your project. Please do not use more than 500 words.
    validations:
      required: true
  - type: textarea
    id: highlights
    attributes:
      label: 🔦 Any other specific thing you want to highlight?
      description: Kindly write a pitch for your project. Please do not use more than 500 words.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: ☝🏽 Before you submit
      description: By submitting this issue, you agree to the following terms
      options:
        - label: I have honestly and correctly filled in this submission form.
          required: true
        - label: I prepared this project during the duration of this hackathon.
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://github.com/mirrorworld-universe/hackathon/CODE_OF_CONDUCT.md)
          required: true
